### PR TITLE
fix  MessageAttributeDataTypes (Number)

### PR DESCRIPTION
**Pull request by bvanloocke**
possible values are Number.int & Number.long

The Amazon SQS Java Messaging Library will fail on this (SNS-SQS) 
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/getting-started.html

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bvanloocke Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=297)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=297) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@bvanloocke Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=297)!

**Comment by bvanloocke** [comment]
error when:

- publishing a request to SNS with MessageAttribute/header and datatype: Number.java.lang.Long
- setup an SNS to SQS consumer (use 'raw message delivery')
- read from the SQS with a JMS consumer (using the Amazon SQS Java Messaging Library)
- JMS consumer will fail (silently) on the MessageAttribute/header with datatype: Number.java.lang.Long


if you use a header/messageAttribute with dataType Number.long it will work.

**Comment by tillkuhn** [comment]
@adriancole Any estimates when this will fix be merged with the base branch and eventually released? This issue currently conflicts with our external monitoring which uses numeric SQS Message Attributes for tracing purposes, in which case the operation annotated as `@SqsListener` will fail before there is any chance to process the message or handle the exception. Thanks!

**Comment by hajdukd** [comment]
Any info on this issue ?

**Comment by maciejwalkowiak** [comment]
@bvanloocke am I getting it right that this change is needed only for compatibility with Amazon SQS JMS based library?

**Comment by maciejwalkowiak** [comment]
Since this will break existing clients we are not able to merge it, but we will take it into account for 3.x.

**Pull request closed without merging**
