### PR TITLE
[#412] SQS client should use custom client configuration if present

### PR DESCRIPTION
**Pull request by ribeaud**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ribeaud Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=413)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=413) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ribeaud Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=413)!

**Comment by ribeaud** [comment]
Sorry, just realized that I did make a branch for this **PR**. Still too 💤 for coding... 😏

**Comment by maciejwalkowiak** [comment]
Thanks for submitting the PR. We applied similar approach to all integrations in https://github.com/spring-cloud/spring-cloud-aws/pull/725

**Pull request closed without merging**
