### PR TITLE
Add integration module as first class support

### PR DESCRIPTION
**Pull request by DarrenForsythe**
fixes gh-589

### CODE REVIEW

**Comment by rieckpil** [comment]
as part of moving the first integration test to Testcontainers, I also fixed formatting and move the IT to `assertThat`: https://github.com/spring-cloud/spring-cloud-aws/pull/588 PR is currently pending

**Comment by maciejwalkowiak** [comment]
Thanks @DarrenForsythe for contribution. I totally agree to run compilation & checkstyle by default. With this PR we have two profiles: `integration-test` and `aws-integration-test`. Since `integration-test` module is included by default, I guess we could just drop `integration-test` profile?

**Comment by DarrenForsythe** [comment]
Failed to see the first profile sitting there, I've removed it in favour of `aws-integration-test` as I think it gives more context to what the profile does vs. having ITs generally run as part of the plan

**Comment by eddumelendez** [comment]
just 2 things:

1. every file modified should be updated to 2020 in the license header. Not a big deal we can do it in the merge process.
2. branch 2.2.x is not using junit5

**Comment by eddumelendez** [comment]
Just noticed that the `@AWSIntegration` annotation is in a base test classes at `spring-cloud-aws-integration-test` module which makes me wonder if should have that annotation at all. May just allowing to run the module with a specific profile is enough. Am I missing something?

**Comment by DarrenForsythe** [comment]
@eddumelendez this will be incompatiable with the 2.2.x branch as is due to the `Tag`, it could be retrofited for 2.2.x and add the JUnit4 `Category` too

**Comment by eddumelendez** [comment]
@DarrenForsythe I was looking into the `Category` but since all the tests depend on `@RunWith(SpringRunner.class)` already I think would be hard to do.  WDYT about https://github.com/spring-cloud/spring-cloud-aws/pull/597#issuecomment-656423285 ?

**Comment by DarrenForsythe** [comment]
The reasoning for the profile was  given issue #588 there is a need to seperate tests that can run locally vs. tests that need an AWS Account. From experience localstack is great, but there can be cases you want a E2E test using an AWS Account, also the build would fail without exlcuding the AWS Tests currently. 

Options in my mind, 



* I _think_ we could try adding the Junit4 annotations to the meta `AWSIntegration` e.g. include JUnit4 as an optional depdenencyh and configure surefire for each? 
* Disable all AWS Integration tests to be re-written with localstack, are the AWS Integration tests being ran at the minute? 
* AWS Open Source Credits? that would limit the tests to CI Still but could activate on CI through other configuration

**Comment by eddumelendez** [comment]
> I think we could try adding the Junit4 annotations to the meta AWSIntegration e.g. include JUnit4 as an optional dependency and configure surefire for each?

The best approach to me and I just did an example so we will be fine. TBH, never did that with inheritance so TIL 😃 . I will apply those changes in the merge process.

**Comment by eddumelendez** [comment]
@DarrenForsythe thank you so much for your contribution. PR is merged in master via f920fc35d4b4371ad9ea0c28ba5d6b7fa80518e7

**Pull request closed without merging**
