### PR TITLE
Fixes SQS Queues shutting down gracefully

### PR DESCRIPTION
**Pull request by mkatircioglu**
* Allow queueStopTimeout can be configurable via SimpleMessageListenerContainerFactory #gh-504
* Increase queueStopTimeout default value in milliseconds to be equal to waitTimeOut #gh-507

### CODE REVIEW

**Comment by eddumelendez** [comment]
@mkatircioglu thanks for the PR! looks good to me but wondering if we can add a configuration property for `queueStopTimeout` which will offer more flexibility. WDYT?

**Comment by mkatircioglu** [comment]
What kind of configuration property do you mean? Since there are some other properties in SimpleMessageListenerContainerFactory which might need to be configured too if we think to give some flexibility. @eddumelendez

**Comment by mkatircioglu** [comment]
Hi @eddumelendez According to my comments, what is your latest opinion? Would you like me to update the PR?

**Comment by maciejwalkowiak** [comment]
Since configuring custom `SimpleMessageListenerContainerFactory` is currently THE way to configure SQS listeners - we do not have configuration properties for SQS (yet) - this PR looks good to me. If you agree @eddumelendez I would be happy to merge it to 2.3.x branch.

**Comment by eddumelendez** [comment]
Thanks for the input. Please go ahead! 👍🏽

**Pull request closed without merging**
