### PR TITLE
Fix for #736 to allow security manager prefix without "/" in the front

### PR DESCRIPTION
**Pull request by hariohmprasath**
## :loudspeaker: Type of change
- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description
The initial code always expected the "prefix" inside "secretmanager" to start with "/" in the front, which not be in true as AWS doesn't impose such restrictions. So the code change takes care of updating the regex to allow 0 or 1 occurrence of "/" as the first character while specifying the prefix inside "secretmanager"

## :bulb: Motivation and Context
#736

## :green_heart: How did you test it?
- All unit testcases passed. 
- Integration test was done using a spring boot application and everything worked as expected

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps
No additional steps required

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hariohmprasath Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hariohmprasath Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hariohmprasath Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hariohmprasath Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=753)!

**Comment by maciejwalkowiak** [comment]
Thanks @hariohmprasath for your contribution. We merged it in https://github.com/awspring/spring-cloud-aws/pull/33

**Pull request closed without merging**
