### PR TITLE
Fix parameterstore to be not eager

### PR DESCRIPTION
**Pull request by mbazhutkin-at-trading-point-com**
* Added onlyApplicationNameLocator to handle cases when we want to use only application name without environment setup
* Added check if application name and default value for locator path are same not to duplicate requests to SSM

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mbazhutkin-at-trading-point-com Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=552)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=552) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mbazhutkin-at-trading-point-com Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=552)!

**Comment by maciejwalkowiak** [comment]
Thanks for contribution! I like the idea but I would flip the property. Instead of `onlyApplicationNameLocator` I believe its simpler to reason if we have `includeProfiles`. This by default must be set to `true` for backward compatibility. Please also include tests.

**Comment by maciejwalkowiak** [comment]
Superseded by #596

**Pull request closed without merging**
