### PR TITLE
Reference documentation enhancements (discussion)

### PR DESCRIPTION
**Pull request by cstettler**
pull request for discussing various reference documentation enhancements
- understanding issues
- formatting issues
- typo and wording fixes

### CODE REVIEW

**Comment by alainsahli** [comment]
Hi @celkins 

We are currently having a look at the JMS client library. As soon as we have a clear position regarding this library we will document it.

**Comment by maciejwalkowiak** [comment]
@cstettler I know it's been a while but perhaps you would be interested to fill the gaps in the current documentation?

**Comment by pivotal-issuemaster** [comment]
@cstettler Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=22)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=22) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by maciejwalkowiak** [comment]
Closing due to lack of feedback.

**Pull request closed without merging**
