### PR TITLE
Fix timeout handling in QueueMessageChannel.java

### PR DESCRIPTION
**Pull request by jorgenota**
## :loudspeaker: Type of change

- [X] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Minor changes to better handle timeout parameter when receiving messages from an SQS queue.

## :bulb: Motivation and Context

I suggest this fixes to align with PollableChannel interface:
- According to javadoc of PollableChannel, MessageChannel.INDEFINITE_TIMEOUT should be used to represent indefinite timeout (instead of 0).
- The timeout parameter of PollableChannel.receive() method represents the timeout in milliseconds (so it should be transformed into seconds when building the ReceiveMessageRequest).

## :pencil: Checklist

- [X ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jorgenota Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jorgenota Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jorgenota Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jorgenota Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=769)!

**Comment by maciejwalkowiak** [comment]
`0` in this case means short polling - not indefinite timeout. With milliseconds - agreed this should be changed, but we need to think if we do it for 2.4 or 3.0. 

Can you move this PR to https://github.com/awspring/spring-cloud-aws? This repository is only used for the 2.2.x maintenance.

**Comment by jorgenota** [comment]
> `0` in this case means short polling - not indefinite timeout. 

Yes, '0' means short polling. According to javadoc of PollableChannel, _receive()_ method  "Receive a message from this channel, blocking **indefinitely** if necessary".  That's why I suggested using MessageChannel.INDEFINITE_TIMEOUT constant in line 204 (instead of 0).

Am I right? Should I move my PR as it is right now (or change only the transformation to seconds)?

 
> Can you move this PR to https://github.com/awspring/spring-cloud-aws? This repository is only used for the 2.2.x maintenance.

Of course, thanks for the clarification.

**Comment by maciejwalkowiak** [comment]
Replaced with https://github.com/awspring/spring-cloud-aws/pull/123

**Pull request closed without merging**
