### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
To get more structure I suggest using this PR template that is almost a direct copy of what is used in https://github.com/getsentry/sentry-java

### CODE REVIEW

**Comment by maciejwalkowiak** [comment]
I'll merge it. We can iterate on it if you'll have some ideas.

**Comment by maciejwalkowiak** [comment]
Ok, apparently I need your approval @eddumelendez.

**Review by eddumelendez — APPROVED** [review]

**Comment by eddumelendez** [comment]
it should go against 2.2.x I think

**Comment by maciejwalkowiak** [comment]
Doesn't `.github` matter only for `master` branch?

**Pull request closed without merging**
