### PR TITLE
CloudWatch metrics autoconfiguration

### PR DESCRIPTION
**Pull request by dkublik**
Hi,
This PR is follow up of https://github.com/spring-projects/spring-boot/pull/11276

Basically I want to add AutoConfiguration for AWS CloudWatch metrics,
but can't add id together with other metrics in SpringBoot as it requires at miniumum
ContextCredentialsAutoConfiguration
RegionProvider 
from spring-cloud-aws. 

Of course I could have implemented it from start, but I guess it wouldn't make sense as it's already there.

Property and bean names are consistent with metrics in Spring Boot actuator.

I know that previous version was deleted by @spencergibb  here: 
https://github.com/spring-cloud/spring-cloud-aws/commit/33778b79d0c5f7553d46941f5e32399708ece704
https://github.com/spring-cloud/spring-cloud-aws/commit/7108d8fa76731f90bf532982c9dc64befe47c94b

but I restored spring-cloud-aws-actuator module as I needed dependency to spring-boot-starter-actuator 
(org.springframework.boot.actuate.autoconfigure.metrics.export.StepRegistryProperties,
org.springframework.boot.actuate.autoconfigure.metrics.export.StepRegistryPropertiesConfigAdapter)

I thought it's better to have separate module for it than force users to download spring-boot-starter-actuator and it's dependencies always when they need spring-cloud-aws-autoconfigure.

also - needed to add 
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-registry-cloudwatch</artifactId>
	<version>${micrometer.version}</version>
</dependency>

in spring-cloud-build-dependencies
(https://github.com/spring-cloud/spring-cloud-build/pull/65)
as can't use ${micrometer.version} directly in spring-cloud-aws,
as it is defined in spring-boot-dependencies and
spring-cloud-build-dependencies is bom (and not parent) of spring-cloud-aws,
and spring-boot-dependencies is parent of spring-cloud-build-dependencies.

I use all of this code in my project in my company - it's working :)

### CODE REVIEW

**Comment by dkublik** [comment]
of curse it won't build until https://github.com/spring-cloud/spring-cloud-build/pull/65 is merged

**Comment by spencergibb** [comment]
@dkublik you should have a chat with @jkschneider. This should go in boot 2.0 but without references to spring-cloud-aws.

**Comment by jkschneider** [comment]
Because CloudWatch support refers to the AWS SDK, we can't put CloudWatch autoconfig in Boot

**Comment by spencergibb** [comment]
@jkschneider so, `micrometer-registry-cloudwatch` is not a managed dependency in boot. Do we need to manage it here?

**Comment by spencergibb** [comment]
Merged with some compatibility changes via d5c8deac23c8840c74c6e6c3bb5507590a693706

**Pull request closed without merging**
