### PR TITLE
Junit method access modifier refactor

### PR DESCRIPTION
**Pull request by DanijelCar**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ x] Refactoring

## :scroll: Description

Junit test metod refactor public to package default access modifier.

## :bulb: Motivation and Context

Test classes, test methods, and lifecycle methods are not required to be public. 

## :pencil: Checklist

- [x ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated reference documentation to reflect the change
- [x ] All tests passing
- [ x] No breaking changes

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@DanijelCar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@DanijelCar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@DanijelCar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@DanijelCar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-aws&pullRequestId=758)!

**Comment by eddumelendez** [comment]
@DanijelCar thank you so much for you contribution but this repository is only active for branch `2.2.x`. For `2.3.x`, look at https://github.com/awspring/spring-cloud-aws

**Pull request closed without merging**
